import { destroy, downloadMedia, fetchCurrentUser } from './client';
import {
  provideAuthPhoneNumber, provideAuthCode, provideAuthPassword, provideAuthRegistration, restartAuth, restartAuthWithQr,
} from './auth';
import {
  fetchChats, fetchFullChat, fetchSuperGroupOnlines, searchChats, requestChatUpdate,
  saveDraft, clearDraft, fetchChat, markChatRead, updateChatMutedState,
  createChannel, editChannelPhoto, joinChannel, leaveChannel, deleteChannel, createGroupChat, editChatPhoto,
  toggleChatPinned, toggleChatArchived, toggleDialogUnread,
  fetchChatFolders, editChatFolder, deleteChatFolder, fetchRecommendedChatFolders,
} from './chats';
import {
  fetchMessages, fetchMessage, sendMessage, pinMessage, deleteMessages, deleteHistory, markMessagesRead,
  searchMessages, searchMessagesGlobal, fetchWebPagePreview, sendPollVote, editMessage, forwardMessages,
  loadPollOptionResults,
} from './messages';
import {
  fetchFullUser, fetchNearestCountry,
  fetchTopUsers, fetchContactList, fetchUsers,
} from './users';
import {
  fetchStickerSets, fetchRecentStickers, fetchFavoriteStickers, fetchFeaturedStickers,
  faveSticker, fetchStickers, fetchSavedGifs, searchStickers, installStickerSet, uninstallStickerSet,
  searchGifs,
} from './symbols';
import {
  updateProfile, checkUsername, updateUsername,
  updateProfilePhoto, uploadProfilePhoto, fetchWallpapers,
} from './account';

export default {
  destroy,
  downloadMedia,
  provideAuthPhoneNumber,
  provideAuthCode,
  provideAuthPassword,
  provideAuthRegistration,
  restartAuth,
  restartAuthWithQr,
  fetchChats,
  fetchMessages,
  fetchMessage,
  sendMessage,
  pinMessage,
  deleteMessages,
  deleteHistory,
  markChatRead,
  updateChatMutedState,
  createChannel,
  editChannelPhoto,
  joinChannel,
  leaveChannel,
  deleteChannel,
  createGroupChat,
  editChatPhoto,
  toggleChatPinned,
  toggleChatArchived,
  fetchChatFolders,
  fetchRecommendedChatFolders,
  editChatFolder,
  deleteChatFolder,
  toggleDialogUnread,
  markMessagesRead,
  searchMessages,
  searchMessagesGlobal,
  fetchWebPagePreview,
  sendPollVote,
  loadPollOptionResults,
  editMessage,
  forwardMessages,
  fetchFullChat,
  fetchSuperGroupOnlines,
  searchChats,
  fetchChat,
  requestChatUpdate,
  saveDraft,
  clearDraft,
  fetchFullUser,
  fetchNearestCountry,
  uploadProfilePhoto,
  updateProfile,
  updateProfilePhoto,
  checkUsername,
  updateUsername,
  fetchWallpapers,
  fetchCurrentUser,
  fetchTopUsers,
  fetchContactList,
  fetchUsers,
  fetchStickerSets,
  fetchRecentStickers,
  fetchFavoriteStickers,
  fetchFeaturedStickers,
  searchStickers,
  faveSticker,
  fetchStickers,
  fetchSavedGifs,
  installStickerSet,
  uninstallStickerSet,
  searchGifs,
};
